name: json

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Echo secrets json
      env:
        SECRET_TEST1_JSON: ${{ toJson(secrets.SECRET_TEST1) }}
        SECRET_TEST2_JSON: ${{ toJson(secrets.SECRET_TEST2) }}
      run: |
        echo ${SECRET_TEST1}
        echo ${SECRET_TEST2}
